                    ### Conexion de Python al DataMart(Redshieft de AWS) de Endesa X ###

#### Datos necesarios para la conexion

**Claves para conectarnos:**

*Server:*

*Ssl mode:* disable

*User_id:* 

*Password:*

*Database:*

*Port:* 5439

In [1]:
############ Requerimientos ####################
# sudo apt-get install python-pip 
# sudo apt-get install libpq-dev
# sudo pip install psycopg2
# sudo pip install sqlalchemy
# sudo pip install sqlalchemy-redshift
##############################################

# Importamos la biblioteca sqlalchemy
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

#>>>>>>>> Introducir los datos de la conexion AQUI <<<<<<<<<<<<< 
DATABASE = ""
USER = ""
PASSWORD = ""
HOST = ""
PORT = "5439"
SCHEMA = "public"      #Por defecto es "public" 


####### Crear la sesion y conexion ############## 
connection_string = "redshift+psycopg2://%s:%s@%s:%s/%s" % (USER,PASSWORD,HOST,str(PORT),DATABASE)
engine = sa.create_engine(connection_string)
session = sessionmaker()
session.configure(bind=engine)
s = session()
SetPath = "SET search_path TO %s" % SCHEMA
s.execute(SetPath)

In [4]:
#>>>>>>>> Escribir la consulta SQL AQUI <<<<<<<<<<<<< 

query = "SELECT * FROM ...;"

In [ ]:
# Ejecucion del cursor sin pd - NO NECESARIO PARA DATAFRAME
rr = s.execute(query)
all_results =  rr.fetchall()

In [2]:
# Importamos la biblioteca para la creacion de dataframes
import pandas as pd

In [5]:
# Creamos el DataFrame
df = pd.read_sql(query, engine)

In [6]:
# Visualizacion de datos
df.head(40)

,cd_nif_cif_cli,origen_contacto,nombre_contacto,nombre_contacto_2,cargo_contacto,area_cargo_contacto,web,telefono_1,telefono_2,telefono_3,...,telefono_valido,check_email_1,check_email_2,email_valido,tipo_telefono,campañas_telefonicas,campañas_mailing,priorizacion_email_1,priorizacion_email_2,priorizacion_mail
0,H50696632,Atenea,JOSE MARIA RIBERA,,,,,976910880,676910880,,...,S,1,0,S,6,2,2,1,0,1
1,H50696632,Atenea,MANUEL BAILE,,,,,None,976530553,,...,S,0,0,N,9,1,0,0,0,0
2,H50696632,Atenea,C P PEDRO IV EL CEREMOSNIOSO 18 -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
3,H33678574,Atenea,CP PEDRO MASAVEU 31 -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
4,H33678574,Atenea,ALONSO FERNANDEZ,,,,,None,985207109,,...,S,0,0,N,9,1,0,0,0,0
5,H85661650,Atenea,ALFREDO PEREZ,,,,,None,654931536,,...,S,0,0,N,6,1,0,0,0,0
6,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
7,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
8,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
9,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
10,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
11,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
12,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
13,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
14,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
15,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
16,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
17,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
18,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
19,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
20,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
21,T,SVE,EDUARDA IZQUIERDO URENDES,,,,,999999999,None,None,...,S,0,0,N,9,1,0,0,0,0
22,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
23,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
24,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
25,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
26,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
27,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
28,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
29,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
30,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
31,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
32,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
33,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
34,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
35,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
36,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
37,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
38,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0
39,T,Atenea,FERIANTES BDA. EL TORCAL -,,,,,None,None,,...,N,0,0,N,0,0,0,0,0,0

In [37]:
# Si desea exportar los datos a excel sustituye df por el nombre del dataframe
#Exportamos una V1 de la BBDD CONTACTOS
df.to_csv('dfv_v1.csv')

In [ ]:
########## Cierre de Sesion ###############
s.close()